extends Node

## Central i18n registry: builds Portuguese (Brasil) and English Translation
## resources from plain dictionaries and registers them with TranslationServer.
## Keeps internal identifiers (flags, ids) untouched — only user-facing text
## keyed by a stable, English, all-caps id goes through tr().
##
## Coverage: settings/main/pause menus, the intro CGI (captions + skip
## confirm), the arrival phone call, Maciota's dialogue, and the mission
## board/objectives. Decorative world signage (shop/lift labels, generic
## exit-door prompts) and the CGI's debug-only preview HUD are intentionally
## NOT covered — see the task's final report for the honest gap list.

const DEFAULT_LOCALE := "pt_BR"
const AVAILABLE_LOCALES: Array[String] = ["pt_BR", "en"]

const PT_BR := {
	"Pista do Cargueiro": "Pista do Cargueiro",
	"Pista do Covil": "Pista do Covil",
	"Achado do Limite Oeste": "Achado do Limite Oeste",
	"Achado do Limite Leste": "Achado do Limite Leste",
	"Achado do Limite Norte": "Achado do Limite Norte",
	"Achado do Limite Sul": "Achado do Limite Sul",
	"Convés do cargueiro, doca leste": "Convés do cargueiro, doca leste",
	"Covil dos Cobras": "Covil dos Cobras",
	"Extremidade leste, além do bairro dos Cobras": "Extremidade leste, além do bairro dos Cobras",
	"COLLECTION_TITLE": "COLECIONÁVEIS",
	"COLLECTION_PROGRESS": "%d de %d encontrados",
	"COLLECTION_LEGACY": "REGISTROS PRESERVADOS DE OUTRA VERSÃO DO MAPA (%d)",
	"COLLECTION_RECORDED": "Achado registrado",
	"COLLECTION_FOUND": "ENCONTRADO",
	"COLLECTION_MISSING": "NÃO ENCONTRADO",
	"BOARD_TITLE_MACIOTA": "QUADRO DE SERVIÇOS · MACIOTA",
	"BOARD_STATUS_MACIOTA": "MACIOTA · CONTATOS E SERVIÇOS",
	"BOARD_NO_SERVICES": "Nenhum serviço novo disponível agora.",
	"BOARD_CLOSE": "FECHAR [ESC]",
	"MISSION_PRIMEIRO_GIRO_TITLE": "Primeiro giro",
	"MISSION_PRIMEIRO_GIRO_DESC": "Busca uma encomenda pra mim no cais. Depois a gente conversa.",
	"MISSION_STATUS_IN_PROGRESS": "Em andamento — retire a encomenda e volte ao Maciota.",
	"OBJ_MEET_MACIOTA": "Encontre Maciota na garagem Westgate · entrada pelo sul",
	"OBJ_BOARD": "Escolha Primeiro giro no quadro da garagem",
	"OBJ_DELIVERY_PICKUP": "Busque a encomenda de Maciota no cais",
	"OBJ_DELIVERY_RETURN": "Leve a encomenda ao Maciota na garagem",
	"OBJ_COMPLETE_RESUME": "Primeiro giro concluído · explore o distrito",
	"OBJ_COMPLETE_REWARD": "Peça entregue · +$150. Maciota: Ferrugem recebeu teu irmão na oficina dos Cobras. O próximo serviço já está no quadro.",
	"MACIOTA_LINE_1": "Dante, né? Obrigado por ter vindo.",
	"MACIOTA_DANTE_REPLY": "Fala logo, cara. Cadê meu irmão?",
	"MACIOTA_FAVOR": "Calma, cara. Eu tô tentando ajudar. Mas você precisa lavar minha mão antes de eu te passar informação.",
	"MACIOTA_BROTHER": "Eu vi teu irmão aqui depois que ele saiu da prisão. Veio à minha oficina. Não sei onde ele está agora.",
	"MACIOTA_LINE_2": "Ele procurava trabalho no cais e perguntou pelos Cobras. Posso te apresentar a quem falou com ele, mas preciso que você me ajude antes.",
	"MACIOTA_LINE_3": "Busca uma encomenda pra mim no cais, meu peixe. Traz aqui e a gente continua essa conversa.",
	"MACIOTA_LINE_4": "O primeiro serviço está no quadro. Quando voltar com a peça, te passo o nome do contato. Cada favor ajuda a puxar mais um fio dessa história.",
	"MACIOTA_LINE_FOLLOWUP": "Vamos continuar seguindo os contatos do teu irmão. Veja o próximo serviço no quadro; não precisa esperar outro dia.",
	"SETTINGS_TITLE": "CONFIGURAÇÕES",
	"SETTINGS_TAB_AUDIO": "ÁUDIO",
	"SETTINGS_TAB_VIDEO": "VÍDEO",
	"SETTINGS_TAB_CONTROLS": "CONTROLES",
	"SETTINGS_LANGUAGE_LABEL": "Idioma:",
	"SETTINGS_LANGUAGE_PT_BR": "Português (Brasil)",
	"SETTINGS_LANGUAGE_EN": "English",
	"SETTINGS_BTN_DEFAULTS": "PADRÕES",
	"SETTINGS_BTN_BACK": "CANCELAR",
	"SETTINGS_BTN_SAVE": "SALVAR E VOLTAR",
	"SETTINGS_MASTER_VOLUME": "Volume Geral (Master):",
	"SETTINGS_MUSIC_VOLUME": "Música & Ambiente:",
	"SETTINGS_SFX_VOLUME": "Efeitos Sonoros (SFX):",
	"SETTINGS_AUDIO_HINT": "Ajuste o som do jogo. Salve para manter suas preferências.",
	"SETTINGS_WINDOW_MODE": "Modo de Janela:",
	"SETTINGS_RESOLUTION": "Resolução da Janela:",
	"SETTINGS_VSYNC": "Sincronização Vertical (VSync):",
	"CONTROL_MOVE_UP": "Mover para Cima / Acelerar",
	"CONTROL_MOVE_DOWN": "Mover para Baixo / Ré",
	"CONTROL_MOVE_LEFT": "Mover para Esquerda / Virar",
	"CONTROL_MOVE_RIGHT": "Mover para Direita / Virar",
	"CONTROL_SPRINT": "Correr (Sprint)",
	"CONTROL_INTERACT": "Interagir / Entrar no Veículo",
	"CONTROL_RADIO_NEXT": "Próxima Estação de Rádio",
	"CONTROL_FIRE": "Atirar / Disparar Arma",
	"CONTROL_RELOAD": "Recarregar Arma (a pé)",
	"CONTROL_WEAPON_WHEEL": "Roda de Armas",
	"CONTROL_PAUSE": "Menu de Pausa",
	"CONTROL_KEY_LEFT_CLICK": "Clique Esquerdo",
	"CONTROL_KEY_RIGHT_CLICK": "Clique Direito",
	"CONTROL_KEY_MIDDLE_CLICK": "Clique do Meio",
	"CONTROL_KEY_MOUSE_WHEEL": "Roda do Mouse",
	"CONTROL_KEY_NONE": "Nenhuma",
	"COMMON_CLOSE": "FECHAR",
	"COMMON_BACK": "VOLTAR",
	"COMMON_UNKNOWN_ERROR": "Erro desconhecido",
	"MENU_SUBTITLE": "METRÓPOLE • CLONE TOP-DOWN",
	"MENU_NEW_GAME": "NOVO JOGO",
	"MENU_LOAD_GAME": "CARREGAR JOGO",
	"MENU_SETTINGS": "CONFIGURAÇÕES",
	"MENU_QUIT": "SAIR DO JOGO",
	"MENU_LOAD_TITLE": "CARREGAR JOGO SALVO",
	"MENU_LOAD_SELECT_SLOT": "Selecione um slot de save para carregar:",
	"MENU_ERROR_NO_SAVEMANAGER": "Erro: SaveManager não está ativo.",
	"MENU_SLOT_EMPTY": "  [%s] --- VAZIO ---",
	"MENU_SLOT_INCOMPATIBLE": "  [%s] ✖ INCOMPATÍVEL / CORROMPIDO: %s",
	"MENU_NO_VALID_SAVES": "Você ainda não tem uma partida salva. Comece um novo jogo.",
	"MENU_LOADING": "Carregando %s...",
	"MENU_LOAD_FAILED": "Falha ao carregar: %s",
	"PAUSE_TITLE": "PAUSA",
	"PAUSE_RESUME": "CONTINUAR",
	"PAUSE_SAVE": "SALVAR JOGO",
	"PAUSE_MAIN_MENU": "MENU PRINCIPAL",
	"PAUSE_SAVE_MODAL_TITLE": "SALVAR JOGO (ESCOLHA UM SLOT)",
	"PAUSE_SELECT_SLOT": "Selecione um slot:",
	"PAUSE_SLOT_INCOMPATIBLE": "  [%s] ✖ INCOMPATÍVEL: %s",
	"PAUSE_SAVED_OK": "✓ Jogo salvo com sucesso no %s!",
	"PAUSE_SAVE_ERROR": "Erro ao salvar: %s",
	"PAUSE_LOADING": "Carregando save...",
	"PAUSE_LOAD_ERROR": "Erro ao carregar: %s",
	"MENU_ACHIEVEMENTS": "CONQUISTAS",
	"PAUSE_ACHIEVEMENTS_TITLE": "CONQUISTAS",
	"PAUSE_ACHIEVEMENTS_PROGRESS": "%d de %d desbloqueadas",
	"PAUSE_ACHIEVEMENTS_LOCKED": "BLOQUEADA",
	"PAUSE_ACHIEVEMENTS_UNLOCKED": "DESBLOQUEADA",
	"COLD_TEMPERATURE_LABEL": "❄️ TEMPERATURA: %d%%",
	"COLD_STATUS_NORMAL": "Normal",
	"COLD_STATUS_HEATED_FIRE": "🔥 AQUECIDO (FOGUEIRA)",
	"COLD_STATUS_HEATED_VEHICLE": "🚗 AQUECIDO (VEÍCULO)",
	"COLD_STATUS_PROTECTED_SUIT": "🧥 PROTEGIDO (TRAJE TÉRMICO)",
	"COLD_STATUS_HYPOTHERMIA_CRITICAL": "💀 HIPOTERMIA CRÍTICA!",
	"COLD_STATUS_FREEZING_WARNING": "⚠️ CONGELANDO! PROCURE ABRIGO",
	"COLD_STATUS_STABLE": "Ambiente Estável",
	"COLD_STATUS_SHELTERED": "Abrigado / Aquecendo",
	"CGI_SKIP_BUTTON": "Pular [Esc]",
	"CGI_SKIP_TITLE": "Pular introdução?",
	"CGI_SKIP_BODY": "Deseja pular a CGI e continuar na rodoviária?",
	"CGI_SKIP_OK": "Pular",
	"CGI_SKIP_CANCEL": "Continuar assistindo",
	"CGI_SPEAKER_CALLER": "VOZ NO TELEFONE",
	"CGI_CALLER_BROTHER_MISSING": "Seu irmão saiu. Foi visto no Harbor. Depois, ninguém mais teve notícia.",
	"CGI_DANTE_WHO_ARE_YOU": "Ele falou com você?",
	"CGI_CAPTION_THAT_NIGHT": "NAQUELA NOITE",
	"PHONE_INCOMING": "CHAMADA RECEBIDA",
	"PHONE_RINGING": "Seu telefone está tocando.",
	"PHONE_ANSWER": "Atender [Enter]",
	"PHONE_CALL_PREFIX": "LIGAÇÃO ·",
	"PHONE_CONTINUE": "Continuar [Enter]",
	"PHONE_HANG_UP": "Encerrar ligação [Enter]",
	"PHONE_LINE_1": "Cheguei. Acabei de descer na rodoviária.",
	"PHONE_LINE_2": "Boa. Vem até a garagem Westgate. A entrada fica do lado sul, de frente para o pátio.",
	"PHONE_LINE_3": "Meu irmão saiu da prisão. Disseram que viram ele por aqui, mas ele não responde. Preciso encontrar ele.",
	"PHONE_LINE_4": "Eu vi teu irmão na minha oficina. Ele procurava trabalho no cais. Vem falar comigo, o sujeito de roxo; tenho um contato que pode ajudar, mas vou precisar de um favor teu.",
	"BOARD_LOCKED_FINISH_MACIOTA": "Termine a conversa com Maciota.",
}

const EN := {
	"COLLECTION_TITLE": "COLLECTIBLES",
	"COLLECTION_PROGRESS": "%d of %d found",
	"COLLECTION_LEGACY": "PRESERVED RECORDS FROM ANOTHER MAP VERSION (%d)",
	"COLLECTION_RECORDED": "Recorded discovery",
	"COLLECTION_FOUND": "FOUND",
	"COLLECTION_MISSING": "NOT FOUND",
	"Pista do Cargueiro": "Freighter Clue",
	"Pista do Covil": "Hideout Clue",
	"Achado do Limite Oeste": "Western Boundary Discovery",
	"Achado do Limite Leste": "Eastern Boundary Discovery",
	"Achado do Limite Norte": "Northern Boundary Discovery",
	"Achado do Limite Sul": "Southern Boundary Discovery",
	"Convés do cargueiro, doca leste": "Freighter deck, east dock",
	"Covil dos Cobras": "Cobras hideout",
	"Extremidade oeste do distrito": "Western edge of the district",
	"Extremidade leste, além do bairro dos Cobras": "Eastern edge, beyond the Cobras neighborhood",
	"Extremidade norte do distrito": "Northern edge of the district",
	"Extremidade sul do distrito": "Southern edge of the district",
	"BOARD_TITLE_MACIOTA": "SERVICE BOARD · MACIOTA",
	"BOARD_STATUS_MACIOTA": "MACIOTA · CONTACTS & JOBS",
	"BOARD_NO_SERVICES": "No new services available right now.",
	"BOARD_CLOSE": "CLOSE [ESC]",
	"MISSION_PRIMEIRO_GIRO_TITLE": "First Run",
	"MISSION_PRIMEIRO_GIRO_DESC": "Pick up a package for me at the docks. Then we'll talk.",
	"MISSION_STATUS_IN_PROGRESS": "In progress — pick up the package and return to Maciota.",
	"OBJ_MEET_MACIOTA": "Find Maciota at the Westgate garage · entrance on the south side",
	"OBJ_BOARD": "Pick First Run from the garage board",
	"OBJ_DELIVERY_PICKUP": "Find Maciota's package at the docks",
	"OBJ_DELIVERY_RETURN": "Bring the package to Maciota at the garage",
	"OBJ_COMPLETE_RESUME": "First Run complete · explore the district",
	"OBJ_COMPLETE_REWARD": "Part delivered · +$150. Maciota: Ferrugem met your brother at the Cobras workshop. The next job is ready on the board.",
	"MACIOTA_LINE_1": "Dante, right? Thanks for coming.",
	"MACIOTA_DANTE_REPLY": "Get to the point, man. Where is my brother?",
	"MACIOTA_FAVOR": "Easy, man. I am trying to help. But you need to scratch my back before I give you information.",
	"MACIOTA_BROTHER": "I saw your brother here after he got out of prison. He came to my shop. I do not know where he is now.",
	"MACIOTA_LINE_2": "He was looking for work at the docks and asked about the Cobras. I can introduce you to people who spoke to him, but I need your help first.",
	"MACIOTA_LINE_3": "Pick up a package for me at the docks, buddy. Bring it here and we'll keep talking.",
	"MACIOTA_LINE_4": "The first job is on the board. Bring the part back and I will give you the contact name. Each favor helps us uncover another piece of the story.",
	"MACIOTA_LINE_FOLLOWUP": "Let us keep tracing the people your brother knew. Check the next job on the board; you do not need to wait another day.",
	"SETTINGS_TITLE": "SETTINGS",
	"SETTINGS_TAB_AUDIO": "AUDIO",
	"SETTINGS_TAB_VIDEO": "VIDEO",
	"SETTINGS_TAB_CONTROLS": "CONTROLS",
	"SETTINGS_LANGUAGE_LABEL": "Language:",
	"SETTINGS_LANGUAGE_PT_BR": "Português (Brasil)",
	"SETTINGS_LANGUAGE_EN": "English",
	"SETTINGS_BTN_DEFAULTS": "DEFAULTS",
	"SETTINGS_BTN_BACK": "CANCEL",
	"SETTINGS_BTN_SAVE": "SAVE & BACK",
	"SETTINGS_MASTER_VOLUME": "Master Volume:",
	"SETTINGS_MUSIC_VOLUME": "Music & Ambience:",
	"SETTINGS_SFX_VOLUME": "Sound Effects (SFX):",
	"SETTINGS_AUDIO_HINT": "Adjust the game audio. Save to keep your preferences.",
	"SETTINGS_WINDOW_MODE": "Window Mode:",
	"SETTINGS_RESOLUTION": "Window Resolution:",
	"SETTINGS_VSYNC": "Vertical Sync (VSync):",
	"CONTROL_MOVE_UP": "Move Up / Accelerate",
	"CONTROL_MOVE_DOWN": "Move Down / Reverse",
	"CONTROL_MOVE_LEFT": "Move Left / Steer",
	"CONTROL_MOVE_RIGHT": "Move Right / Steer",
	"CONTROL_SPRINT": "Sprint",
	"CONTROL_INTERACT": "Interact / Enter Vehicle",
	"CONTROL_RADIO_NEXT": "Next Radio Station",
	"CONTROL_FIRE": "Fire / Shoot Weapon",
	"CONTROL_RELOAD": "Reload Weapon (on foot)",
	"CONTROL_WEAPON_WHEEL": "Weapon Wheel",
	"CONTROL_PAUSE": "Pause Menu",
	"CONTROL_KEY_LEFT_CLICK": "Left Click",
	"CONTROL_KEY_RIGHT_CLICK": "Right Click",
	"CONTROL_KEY_MIDDLE_CLICK": "Middle Click",
	"CONTROL_KEY_MOUSE_WHEEL": "Mouse Wheel",
	"CONTROL_KEY_NONE": "None",
	"COMMON_CLOSE": "CLOSE",
	"COMMON_BACK": "BACK",
	"COMMON_UNKNOWN_ERROR": "Unknown error",
	"MENU_SUBTITLE": "METROPOLIS • TOP-DOWN CLONE",
	"MENU_NEW_GAME": "NEW GAME",
	"MENU_LOAD_GAME": "LOAD GAME",
	"MENU_SETTINGS": "SETTINGS",
	"MENU_QUIT": "QUIT GAME",
	"MENU_LOAD_TITLE": "LOAD SAVED GAME",
	"MENU_LOAD_SELECT_SLOT": "Select a save slot to load:",
	"MENU_ERROR_NO_SAVEMANAGER": "Error: SaveManager is not active.",
	"MENU_SLOT_EMPTY": "  [%s] --- EMPTY ---",
	"MENU_SLOT_INCOMPATIBLE": "  [%s] ✖ INCOMPATIBLE / CORRUPT: %s",
	"MENU_NO_VALID_SAVES": "You do not have a saved game yet. Start a new game.",
	"MENU_LOADING": "Loading %s...",
	"MENU_LOAD_FAILED": "Failed to load: %s",
	"PAUSE_TITLE": "PAUSED",
	"PAUSE_RESUME": "RESUME",
	"PAUSE_SAVE": "SAVE GAME",
	"PAUSE_MAIN_MENU": "MAIN MENU",
	"PAUSE_SAVE_MODAL_TITLE": "SAVE GAME (CHOOSE A SLOT)",
	"PAUSE_SELECT_SLOT": "Select a slot:",
	"PAUSE_SLOT_INCOMPATIBLE": "  [%s] ✖ INCOMPATIBLE: %s",
	"PAUSE_SAVED_OK": "✓ Game saved successfully to %s!",
	"PAUSE_SAVE_ERROR": "Error saving: %s",
	"PAUSE_LOADING": "Loading save...",
	"PAUSE_LOAD_ERROR": "Error loading: %s",
	"MENU_ACHIEVEMENTS": "ACHIEVEMENTS",
	"PAUSE_ACHIEVEMENTS_TITLE": "ACHIEVEMENTS",
	"PAUSE_ACHIEVEMENTS_PROGRESS": "%d of %d unlocked",
	"PAUSE_ACHIEVEMENTS_LOCKED": "LOCKED",
	"PAUSE_ACHIEVEMENTS_UNLOCKED": "UNLOCKED",
	"COLD_TEMPERATURE_LABEL": "❄️ TEMPERATURE: %d%%",
	"COLD_STATUS_NORMAL": "Normal",
	"COLD_STATUS_HEATED_FIRE": "🔥 WARM (CAMPFIRE)",
	"COLD_STATUS_HEATED_VEHICLE": "🚗 WARM (VEHICLE)",
	"COLD_STATUS_PROTECTED_SUIT": "🧥 PROTECTED (THERMAL SUIT)",
	"COLD_STATUS_HYPOTHERMIA_CRITICAL": "💀 CRITICAL HYPOTHERMIA!",
	"COLD_STATUS_FREEZING_WARNING": "⚠️ FREEZING! FIND SHELTER",
	"COLD_STATUS_STABLE": "Stable Environment",
	"COLD_STATUS_SHELTERED": "Sheltered / Warming up",
	"CGI_SKIP_BUTTON": "Skip [Esc]",
	"CGI_SKIP_TITLE": "Skip the intro?",
	"CGI_SKIP_BODY": "Skip the CGI and continue at the bus terminal?",
	"CGI_SKIP_OK": "Skip",
	"CGI_SKIP_CANCEL": "Keep watching",
	"CGI_SPEAKER_CALLER": "VOICE ON THE PHONE",
	"CGI_CALLER_BROTHER_MISSING": "Your brother left. He was seen at the Harbor. After that, no one heard from him again.",
	"CGI_DANTE_WHO_ARE_YOU": "Did he talk to you?",
	"CGI_CAPTION_THAT_NIGHT": "THAT NIGHT",
	"PHONE_INCOMING": "INCOMING CALL",
	"PHONE_RINGING": "Your phone is ringing.",
	"PHONE_ANSWER": "Answer [Enter]",
	"PHONE_CALL_PREFIX": "CALL ·",
	"PHONE_CONTINUE": "Continue [Enter]",
	"PHONE_HANG_UP": "Hang up [Enter]",
	"PHONE_LINE_1": "I'm here. Just got off the bus at the terminal.",
	"PHONE_LINE_2": "Good. Come to the Westgate garage. The entrance is on the south side, facing the yard.",
	"PHONE_LINE_3": "My brother got out of prison. They said he was seen around here, but he's not answering. I need to find him.",
	"PHONE_LINE_4": "I saw your brother at my shop. He was looking for work at the docks. Come see me, the guy in purple. I have a contact who may help, but I will need a favor.",
	"BOARD_LOCKED_FINISH_MACIOTA": "Finish talking to Maciota.",
}


func _init() -> void:
	_register(&"pt_BR", PT_BR)
	_register(&"en", EN)


func _register(locale: StringName, table: Dictionary) -> void:
	var translation := Translation.new()
	translation.locale = locale
	for key in table:
		translation.add_message(StringName(key), String(table[key]))
	TranslationServer.add_translation(translation)


static func is_supported(locale: String) -> bool:
	return AVAILABLE_LOCALES.has(locale)
