extends SceneTree
const GRID := preload("res://systems/inventory/GridInventory.gd")
const ECONOMY := preload("res://systems/economy/Economy.gd")
const STATE := preload("res://runtime/GameState.gd")
var failures := 0
var checks := 0
func _initialize() -> void: run.call_deferred()
func check(ok: bool,label: String) -> void:
	checks+=1
	if not ok: failures+=1; push_error(label)
	print("GRID ","PASS " if ok else "FAIL ",label)
func run() -> void:
	var economy=ECONOMY.new()
	economy.enable_grid_inventory()
	check(economy.grid_snapshot().bag=="" and GRID.dimensions(economy.grid_snapshot(),"pockets")==Vector2i(2,1),"start with only two pockets")
	check(economy.grid_equip_bag("backpack"),"equip 12-cell backpack")
	check(not economy.grid_equip_bag("handbag"),"one bag only")
	var data:=GRID.empty(); data.bag="backpack"
	check(GRID.add(data,"storage","weapon:hunting_rifle",1)==0,"four-cell long gun fits one full row")
	check(GRID.extent(data.storage[0])==Vector2i(4,1),"long gun footprint is 4x1")
	check(not GRID.fits(data.storage,Vector2i(4,3),data.storage[0],Vector2i(1,1)),"long gun cannot wrap across rows")
	check(GRID.add(data,"storage","ammo:pistol",199)==0 and data.storage.size()==4,"199 spare rounds take three cells")
	check(data.storage[1].amount==99 and data.storage[2].amount==99 and data.storage[3].amount==1,"ammo stacks stop at 99")
	check(GRID.validate(data),"spatial snapshot validates")
	var malformed:=data.duplicate(true); malformed.storage[1].x=0; malformed.storage[1].y=0
	check(not GRID.validate(malformed),"overlapping save rejected")
	malformed=data.duplicate(true); malformed.storage[1].amount=100
	check(not GRID.validate(malformed),"oversized ammo save rejected")
	check(economy.grant_weapon("pistol"),"starter pistol granted")
	check(economy.add_ammo("pistol",27),"fill linked ammo to 99")
	check(economy.snapshot().weapons.pistol.magazine+economy.snapshot().weapons.pistol.reserve==99,"99 rounds travel with the gun")
	check(economy.add_ammo("pistol",198),"additional ammo goes into inventory")
	check(GRID.count(economy.grid_snapshot(),"ammo:pistol")==198,"excess is spatial, not hidden reserve")
	check(economy.consume_ammo("pistol",12) and economy.reload_weapon("pistol"),"shoot and reload pull spatial reserve")
	check(economy.get_ammo("pistol").magazine+economy.get_ammo("pistol").reserve==285,"reload conserves ammunition")
	check(economy.grant_item("apple",3),"food occupies space")
	var uid:=economy.grid_drop_bag("harbor","",Vector3(12,.1,14))
	check(uid>0 and economy.grid_snapshot().bag=="","drop clears only equipped bag")
	var restored=ECONOMY.new()
	check(restored.restore_snapshot(JSON.parse_string(JSON.stringify(economy.snapshot()))),"JSON save round trip with dropped bag")
	check(restored.grid_recover_bag(uid),"recover bag after save/load")
	check(not restored.grid_recover_bag(uid),"cannot duplicate a recovered bag")
	check(GRID.count(restored.grid_snapshot(),"apple")==3,"contents recovered intact")
	check(restored.consume_item("apple") and GRID.count(restored.grid_snapshot(),"apple")==2,"consume removes one spatial item")
	var before: Dictionary = restored.snapshot()
	check(not restored.grid_move("storage",0,"pockets",Vector2i(1,0)) and restored.snapshot()==before,"failed placement is atomic")
	var full=ECONOMY.new(); full.enable_grid_inventory(); full.grant_weapon("pistol"); full.add_ammo("pistol",27)
	full.grant_item("garage_part"); full.grant_item("water",5); full.grant_reward("budget",1000)
	var wallet: Dictionary=full.snapshot()
	check(not full.buy_ammo("pistol",99,"no_space") and full.snapshot()==wallet,"full inventory purchase does not debit or add ammo")
	check(not full.grant_item("apple"),"full pockets refuse pickups")
	var state=STATE.new(); state.economy.enable_grid_inventory(); state.grant_weapon("hunting_rifle"); state.grant_weapon("pistol")
	state.economy.grid_equip_bag("handbag")
	check(not state.equip_weapon("hunting_rifle") and state.equip_weapon("pistol"),"handbag blocks long gun but allows pistol")
	state.set_location("harbor","maciota")
	check(state.equipped_weapon=="fists" and not state.equip_weapon("pistol") and not state.can_attack(),"garage remains weapon-free")
	state.set_location("harbor","")
	check(state.equip_weapon("pistol"),"weapon permission returns outside garage")
	var legacy=ECONOMY.new(); legacy.grant_weapon("ak47"); legacy.add_ammo("ak47",1000); legacy.grant_item("first_aid",10)
	var total: int=legacy.get_ammo("ak47").magazine+legacy.get_ammo("ak47").reserve
	legacy.enable_grid_inventory()
	var linked: Dictionary=legacy.snapshot().weapons.ak47
	check(int(linked.magazine)+int(linked.reserve)+GRID.count(legacy.grid_snapshot(),"ammo:ak47",false)==total,"legacy migration preserves every round")
	check(GRID.count(legacy.grid_snapshot(),"first_aid",false)==10,"legacy supplies preserved outside trunk")
	var cheated=ECONOMY.new(); cheated.enable_grid_inventory(); cheated.activate_arsenal_cheat()
	check(cheated.get_ammo("pistol").reserve>=9999,"existing cheat keeps access to its explicit extra ammo")
	check(ECONOMY.validate_snapshot(cheated.snapshot()),"cheated inventory still has valid unique physical ownership")
	var copied=ECONOMY.new()
	check(copied.restore_snapshot(cheated.snapshot()) and not copied.cheat_all_weapons,"save excludes temporary cheat arsenal")
	print("GRID_RESULT checks=",checks," failures=",failures)
	quit(1 if failures else 0)
