extends SceneTree
var failures := 0
func _initialize() -> void: run.call_deferred()
func check(ok: bool, label: String) -> void:
	print(("PASS " if ok else "FAIL ")+label)
	if not ok: failures += 1
func run() -> void:
	var mix := root.get_node("MissionVoiceMixer")
	mix.set_process(false)
	var settings := root.get_node("SettingsManager")
	var old_sfx: float = settings.sfx_volume
	var old_music: float = settings.music_volume
	settings.set_sfx_volume(.45)
	settings.set_music_volume(.35)
	var stage := Node.new()
	root.add_child(stage)
	var voice := AudioStreamPlayer.new()
	stage.add_child(voice)
	mix.track(voice)
	mix.set_process(false)
	voice.stream = preload("res://ExpressiveVoice.gd").line("Teste de prioridade de voz.","dante",2.0)
	voice.play()
	mix._process(.5)
	var world := AudioServer.get_bus_index("MissionWorld")
	check(AudioServer.get_bus_volume_db(world) == -16.0,"speech lowers all world audio by 16 dB")
	check(AudioServer.get_bus_send(AudioServer.get_bus_index("SFX")) == &"MissionWorld" and AudioServer.get_bus_send(AudioServer.get_bus_index("Music")) == &"MissionWorld","effects and music share the world reduction")
	check(voice.bus == &"Dialogue" and AudioServer.get_bus_send(AudioServer.get_bus_index("Dialogue")) == &"Master","voice bypasses the attenuation")
	check(is_equal_approx(AudioServer.get_bus_volume_db(AudioServer.get_bus_index("SFX")),linear_to_db(.45)),"user effects setting remains intact")
	voice.stop()
	mix._process(.5)
	check(AudioServer.get_bus_volume_db(world) == -16.0,"short dialogue pauses retain focus")
	settings.set_sfx_volume(.2)
	mix._process(2.0)
	check(is_zero_approx(AudioServer.get_bus_volume_db(world)),"interrupted voice releases world volume")
	check(is_equal_approx(AudioServer.get_bus_volume_db(AudioServer.get_bus_index("Dialogue")),linear_to_db(.2)),"voice follows changes to the user's effects volume")
	voice.play()
	mix._process(.5)
	stage.free()
	mix._process(2.0)
	check(is_zero_approx(AudioServer.get_bus_volume_db(world)),"scene removal cannot leave world volume reduced")
	settings.set_sfx_volume(old_sfx)
	settings.set_music_volume(old_music)
	print("MISSION_VOICE_MIX failures=",failures)
	quit(1 if failures else 0)
