extends SceneTree
const ENGINE = preload("res://audio/VehicleEngineSound.gd")
func _initialize() -> void: call_deferred("run")
func run() -> void:
	assert(ENGINE.family_for_vehicle("maciota_350z") == "vq35")
	var layers := ENGINE.get_layer_streams("vq35","maciota_350z")
	assert(layers.size() == 7)
	for stream in layers:
		assert(stream is AudioStreamWAV and stream.data.size() > 10000)
		var peak := 0
		for i in range(0,stream.data.size(),2): peak = maxi(peak,absi(stream.data.decode_s16(i)))
		assert(peak > 100 and peak < 32767)
	var actor := Node2D.new()
	root.add_child(actor)
	var player := AudioStreamPlayer2D.new()
	actor.add_child(player)
	var engine := ENGINE.new()
	engine.bind(player,"maciota_350z")
	for i in 600: engine.update(player,float(i)/600*105,150,.65,1.0/60,"maciota_350z")
	assert(engine.gear > 1 and engine.engine_rpm > 1000)
	for i in 60: engine.update(player,0.0,150,0.0,1.0/60,"maciota_350z")
	assert(engine.gear == 1 and engine.engine_rpm < 1000,"a hard stop selects first and settles back to idle")
	engine.stop()
	player.stop()
	print("PASS VQ35: seven non-clipping layers, vehicle binding and gear shifts")
	quit()
