extends SceneTree
var failures: Array[String] = []
func _initialize() -> void: run.call_deferred()
func check(value: bool, label: String) -> void:
	if not value: failures.append(label); push_error(label)
func run() -> void:
	var state = load("res://runtime/GameState.gd").new()
	var store = load("res://runtime/SaveStore.gd").new()
	store.path = "user://tests/full_save_%d/progress.json"%Time.get_ticks_usec()
	state.economy.grant_reward("first",25)
	check(store.save(state)==OK,"First complete save published")
	state.economy.grant_reward("second",75)
	check(store.save(state)==OK,"Second save published with backup")
	var loaded = load("res://runtime/GameState.gd").new()
	check(store.load_into(loaded).get("ok",false) and loaded.economy.balance==100,"Newest balance restored")
	var broken := FileAccess.open(store.path,FileAccess.WRITE)
	broken.store_string("{ interrupted")
	broken.close()
	check(store.load_into(loaded).get("recovered",false) and loaded.economy.balance==25,"Interrupted primary recovers last valid backup")
	check(store.save(loaded)==OK,"Recovered game can save without deleting corrupt evidence")
	check(store.load_into(loaded).get("ok",false) and loaded.economy.balance==25,"Recovered save is readable again")
	var invalid: Dictionary = loaded.snapshot()
	invalid.combat = {"health":-1,"armor":0,"crime_points":0,"hidden_time":0}
	check(not loaded.restore_snapshot(invalid),"Invalid combat health rejected before state changes")
	check(loaded.economy.balance==25,"Rejected save preserves live progression")
	invalid = loaded.snapshot()
	invalid.world.vehicles = [{"archetype":"sport_coupe","position":[0,0,0],"yaw":0,"health":999999,"region":"harbor"}]
	check(not loaded.restore_snapshot(invalid),"Impossible vehicle state rejected")
	loaded.grant_weapon("pistol")
	loaded.equip_weapon("pistol")
	loaded.set_location("harbor","maciota")
	check(store.save(loaded)==OK,"Garage state saved")
	var garage = load("res://runtime/GameState.gd").new()
	check(store.load_into(garage).get("ok",false) and not garage.weapons_allowed() and garage.owns_weapon("pistol"),"Restore holsters weapon while preserving ownership")
	var thermal = preload("res://runtime/cold/ThermalState.gd").new()
	thermal.temperature = 27.5
	thermal.exposure = 44.0
	thermal.weather_clock = 123.0
	garage.world_state.cold = thermal.snapshot()
	check(store.save(garage)==OK,"Cold state saves with the full session")
	var cold_loaded = load("res://runtime/GameState.gd").new()
	var cold_result: Dictionary = store.load_into(cold_loaded)
	var saved_thermal: Dictionary = cold_loaded.world_state.get("cold",{})
	var same_thermal: bool = cold_result.get("ok",false) and saved_thermal.size()==thermal.snapshot().size()
	for key in thermal.snapshot():
		same_thermal = same_thermal and saved_thermal.has(key) and float(saved_thermal[key])==float(thermal.snapshot()[key])
	check(same_thermal,"Full save preserves temperature, exposure and weather across JSON numeric types")
	invalid = cold_loaded.snapshot()
	invalid.world.cold.temperature = -1
	check(not cold_loaded.restore_snapshot(invalid) and cold_loaded.world_state.cold.temperature==27.5,"Invalid cold state cannot partially change the live save")
	var reward_state = load("res://runtime/GameState.gd").new()
	var reward_definition := {"id":"mountain_cargo_plane_treasure_01","kind":"cash","amount":1800}
	check(reward_state.economy.grant_world_reward(reward_definition).ok,"Synthetic world reward granted")
	reward_state.world_state.rewards.append(reward_definition.id)
	var reward_snapshot: Dictionary = JSON.parse_string(JSON.stringify(reward_state.snapshot()))
	var reward_loaded = load("res://runtime/GameState.gd").new()
	check(reward_loaded.restore_snapshot(reward_snapshot) and reward_loaded.economy.balance==1800,"Reward result and collected marker restore together")
	var reward_retry: Dictionary = reward_loaded.economy.grant_world_reward(reward_definition)
	check(reward_retry.ok and not reward_retry.changed and reward_loaded.economy.balance==1800,"Loaded reward receipt blocks duplicate cash")
	var inconsistent := reward_snapshot.duplicate(true)
	inconsistent.economy = load("res://systems/economy/Economy.gd").new().snapshot()
	check(not reward_loaded.restore_snapshot(inconsistent) and reward_loaded.economy.balance==1800,"Collected marker without complete grant is rejected atomically")
	var receipt_only = load("res://runtime/GameState.gd").new()
	check(receipt_only.economy.grant_world_reward(reward_definition).ok,"Synthetic interrupted marker state created")
	var receipt_snapshot: Dictionary = JSON.parse_string(JSON.stringify(receipt_only.snapshot()))
	var receipt_loaded = load("res://runtime/GameState.gd").new()
	check(receipt_loaded.restore_snapshot(receipt_snapshot),"Receipt without marker remains loadable for reconciliation")
	var reconciled: Dictionary = receipt_loaded.economy.grant_world_reward(reward_definition)
	if reconciled.ok and not receipt_loaded.world_state.rewards.has(reward_definition.id): receipt_loaded.world_state.rewards.append(reward_definition.id)
	check(reconciled.ok and not reconciled.changed and receipt_loaded.economy.balance==1800 and receipt_loaded.restore_snapshot(receipt_loaded.snapshot()),"Retry repairs marker without repeating reward")
	var orphan_weapon: Dictionary = load("res://runtime/GameState.gd").new().snapshot()
	orphan_weapon.economy.transactions["reward:mountain_cargo_plane_smg_01"] = {"kind":"reward","item":"mountain_cargo_plane_smg_01","amount":0}
	check(not receipt_loaded.restore_snapshot(orphan_weapon) and receipt_loaded.economy.balance==1800,"Weapon reward receipt without granted weapon is rejected")
	var canonical_state = load("res://runtime/GameState.gd").new()
	check(canonical_state.canonical_campaign.complete_beat("prologue_call_completed"),"Physical prologue event advances canonical ledger")
	var canonical_loaded = load("res://runtime/GameState.gd").new()
	check(canonical_loaded.restore_snapshot(JSON.parse_string(JSON.stringify(canonical_state.snapshot()))) and canonical_loaded.canonical_campaign.snapshot().current_stage=="bus_terminal_arrival","Canonical beat survives synthetic save/load")
	var armor_state = load("res://runtime/GameState.gd").new()
	armor_state.economy.grant_reward("armor_funds",500)
	var armor_purchase: Dictionary = armor_state.economy.purchase_body_armor(20,100,"synthetic_armor")
	if armor_purchase.ok: armor_state.combat_state = {"health":100,"armor":armor_purchase.armor,"crime_points":0,"hidden_time":0,"customization":{}}
	var armor_loaded = load("res://runtime/GameState.gd").new()
	check(armor_purchase.ok and armor_loaded.restore_snapshot(JSON.parse_string(JSON.stringify(armor_state.snapshot()))) and armor_loaded.economy.balance==0 and int(armor_loaded.combat_state.armor)==100,"Successful armor result, debit and combat protection restore together")
	print("FULL_SAVE ","PASS" if failures.is_empty() else "FAIL"," failures=",failures.size())
	quit(0 if failures.is_empty() else 1)
