extends SceneTree
var failures: Array[String] = []
var world
func _initialize() -> void: call_deferred("run")
func check(ok: bool, message: String) -> void:
	if not ok: failures.append(message)
func settle() -> void:
	for i in 3: await physics_frame
func use_target(key: String) -> void:
	world.player.teleport(world.maciota_place.interaction_points[key]+Vector3.UP*.04)
	await settle()
	check(world.session.interact_nearest(),"Interaction "+key)
	world.session.close_dialogue()
func run() -> void:
	world = load("res://Main.tscn").instantiate()
	root.add_child(world)
	await settle()
	var session = world.session
	check(session.no_save,"Test requires --no-save")
	check(not session.interact_nearest(),"No remote interaction")
	world.player.teleport(world.maciota_place.entry_position+Vector3(0,.04,.6))
	await settle()
	check(session.interact_nearest(),"Physical garage entrance")
	check(session.inside and world.camera.locked,"Garage camera locked")
	check(not session.progression.can_attack(),"Garage attack blocked")
	check(not session.progression.equip_weapon("pistol"),"Garage equip blocked")
	await use_target("mechanic")
	check(session.progression.snapshot().phase == "meet_maciota","Order protected")
	await use_target("maciota")
	check(session.progression.snapshot().phase == "talk_mechanic","Maciota advances")
	await use_target("mechanic")
	check(session.progression.snapshot().phase == "collect_part","Mechanic advances")
	check(world.maciota_place.part_visual.visible,"Part now visible")
	await use_target("part")
	check(session.progression.snapshot().inventory.get("garage_part",0) == 1,"Collect exactly one")
	check(not world.maciota_place.part_visual.visible,"Part removed")
	await use_target("maciota")
	check(session.progression.snapshot().phase == "complete","Complete mission")
	await use_target("maciota")
	check(session.progression.snapshot().completed_missions.size() == 1,"No duplicate reward")
	world.player.teleport(world.maciota_place.exit_position+Vector3(0,.04,-.5))
	await settle()
	check(session.interact_nearest(),"Physical garage exit")
	check(not session.inside and not world.camera.locked,"Outdoor camera restored")
	check(session.progression.can_attack(),"Outdoor weapon policy restored")
	var block := StaticBody3D.new()
	var shape := CollisionShape3D.new()
	var box := BoxShape3D.new()
	box.size = Vector3(2,2,2)
	shape.shape = box
	block.add_child(shape)
	block.position = world.maciota_place.interior_spawn+Vector3.UP
	world.add_child(block)
	await settle()
	check(not session.transition(true),"Occupied checkpoint rejected")
	check(not session.inside,"Failed transition preserves zone")
	block.free()
	await settle()
	check(session.transition(true,false),"Enter for save checkpoint")
	session.save_path = "user://tests/session_"+str(Time.get_ticks_usec())+".json"
	session.no_save = false
	session.save_checkpoint()
	check(session.transition(false,false),"Leave without replacing save")
	session.progression = load("res://systems/Progression.gd").new()
	check(session.load_checkpoint(),"Load physical checkpoint")
	check(session.inside and world.camera.locked,"Loaded room and camera")
	check(session.progression.snapshot().phase == "complete","Loaded mission")
	check(not session.progression.can_attack(),"Loaded garage weapon lock")
	check(world.player.position.distance_to(world.maciota_place.interior_spawn) < .1,"Loaded physical position")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(session.save_path))
	for failure in failures: push_error(failure)
	print("V2_SESSION ","PASS" if failures.is_empty() else "FAIL", " failures=",failures.size())
	world.free()
	quit(0 if failures.is_empty() else 1)
