class_name OpeningCutsceneTimeline
extends RefCounted

## Montagem V2: cotidiano, vínculo familiar, notícia e decisão; depois viagem.
## Durações somam 41,5 segundos; transições entram dentro dessas durações.

const DESTINATION_BEAT: StringName = &"bus_terminal_arrival"
const TOTAL_DURATION_SECONDS := 41.5

const SHOTS: Array[Dictionary] = [
	{
		"id": &"morning_coffee",
		"texture": "res://cutscenes/opening/frames/frame_v2_morning_coffee.png",
		"duration": 4.0,
		"enter": &"fade",
		"transition_duration": 0.6,
		"zoom_from": 1.00,
		"zoom_to": 1.04,
		"pan_from": Vector2.ZERO,
		"pan_to": Vector2(18.0, -8.0),
		"cues": [
			{"at": 0.4, "id": &"traffic_distant"},
		],
		"captions": [],
	},
	{
		"id": &"family_photos",
		"texture": "res://cutscenes/opening/frames/frame_v2_family_photos.png",
		"duration": 3.5,
		"enter": &"crossfade",
		"transition_duration": 0.5,
		"zoom_from": 1.00,
		"zoom_to": 1.05,
		"pan_from": Vector2.ZERO,
		"pan_to": Vector2(-20.0, 8.0),
		"cues": [],
		"captions": [],
	},
	{
		"id": &"phone_closeup",
		"texture": "res://cutscenes/opening/frames/frame_v2_phone.png",
		"duration": 3.0,
		"enter": &"cut",
		"transition_duration": 0.0,
		"zoom_from": 1.02,
		"zoom_to": 1.07,
		"pan_from": Vector2(22.0, 0.0),
		"pan_to": Vector2(-18.0, -5.0),
		"cues": [
			{"at": 0.0, "id": &"phone_ring_old"},
			{"at": 1.4, "id": &"phone_vibrate_wood"},
		],
		"captions": [],
	},
	{
		"id": &"call_reaction",
		"texture": "res://cutscenes/opening/frames/frame_v2_call.png",
		"duration": 7.0,
		"enter": &"cut",
		"transition_duration": 0.0,
		"zoom_from": 1.00,
		"zoom_to": 1.06,
		"pan_from": Vector2.ZERO,
		"pan_to": Vector2(-22.0, -10.0),
		"cues": [
			{"at": 0.0, "id": &"phone_answer_click"},
			{"at": 0.7, "id": &"voice_caller_brother_missing"},
			{"at": 5.2, "id": &"voice_dante_who_are_you"},
		],
		"captions": [
			{"from": 0.7, "to": 4.8, "speaker": "CGI_SPEAKER_CALLER", "text": "CGI_CALLER_BROTHER_MISSING"},
			{"from": 5.2, "to": 6.8, "speaker": "DANTE", "text": "CGI_DANTE_WHO_ARE_YOU"},
		],
	},
	{
		"id": &"quiet_decision",
		"texture": "res://cutscenes/opening/frames/frame_v2_decision.png",
		"duration": 3.0,
		"enter": &"cut",
		"transition_duration": 0.0,
		"zoom_from": 1.00,
		"zoom_to": 1.04,
		"pan_from": Vector2(0.0, 8.0),
		"pan_to": Vector2(8.0, -8.0),
		"cues": [
			{"at": 0.2, "id": &"photo_paper"},
		],
		"captions": [],
	},
	{
		"id": &"backpack_departure",
		"texture": "res://cutscenes/opening/frames/frame_06_backpack_departure.png",
		"duration": 3.5,
		"enter": &"crossfade",
		"transition_duration": 0.3,
		"zoom_from": 1.00,
		"zoom_to": 1.035,
		"pan_from": Vector2(14.0, 0.0),
		"pan_to": Vector2(-14.0, 0.0),
		"cues": [
			{"at": 0.0, "id": &"backpack_buckle"},
			{"at": 0.55, "id": &"chair_creak"},
			{"at": 1.0, "id": &"floor_steps"},
		],
		"captions": [{"from": 0.5, "to": 3.0, "speaker": "", "text": "CGI_CAPTION_THAT_NIGHT"}],
	},
	{
		"id": &"door_exit",
		"texture": "res://cutscenes/opening/frames/frame_07_door_exit.png",
		"duration": 3.5,
		"enter": &"crossfade",
		"transition_duration": 0.3,
		"zoom_from": 1.00,
		"zoom_to": 1.025,
		"pan_from": Vector2.ZERO,
		"pan_to": Vector2(12.0, 2.0),
		"cues": [
			{"at": 0.0, "id": &"door_open"},
			{"at": 0.2, "id": &"rain_gust"},
			{"at": 2.5, "id": &"door_close"},
		],
		"captions": [],
	},
	{
		"id": &"bus_highway",
		"texture": "res://cutscenes/opening/frames/frame_08_bus_highway.png",
		"duration": 4.5,
		"enter": &"crossfade",
		"transition_duration": 0.6,
		"zoom_from": 1.00,
		"zoom_to": 1.035,
		"pan_from": Vector2(18.0, 0.0),
		"pan_to": Vector2(-20.0, 1.0),
		"cues": [
			{"at": 0.0, "id": &"bus_diesel_exterior"},
			{"at": 0.0, "id": &"rain_city"},
			{"at": 0.0, "id": &"music_travel"},
		],
		"captions": [],
	},
	{
		"id": &"dante_bus_interior",
		"texture": "res://cutscenes/opening/frames/frame_09_dante_bus_interior.png",
		"duration": 5.0,
		"enter": &"cut",
		"transition_duration": 0.0,
		"zoom_from": 1.00,
		"zoom_to": 1.04,
		"pan_from": Vector2.ZERO,
		"pan_to": Vector2(8.0, -5.0),
		"cues": [
			{"at": 0.0, "id": &"bus_diesel_interior"},
			{"at": 0.25, "id": &"bus_wiper"},
			{"at": 2.7, "id": &"bus_body_rattle"},
		],
		"captions": [],
	},
	{
		"id": &"bus_terminal_arrival",
		"texture": "res://cutscenes/opening/frames/frame_10_bus_terminal_arrival.png",
		"duration": 4.5,
		"enter": &"crossfade",
		"transition_duration": 0.35,
		"zoom_from": 1.00,
		"zoom_to": 1.04,
		"pan_from": Vector2(12.0, 0.0),
		"pan_to": Vector2(-8.0, -3.0),
		"cues": [
			{"at": 0.0, "id": &"bus_brakes"},
			{"at": 0.0, "id": &"terminal_ambience"},
			{"at": 0.6, "id": &"terminal_pa_distant"},
			{"at": 3.2, "id": &"bus_air_brake"},
		],
		"captions": [
			{"from": 2.2, "to": 4.0, "speaker": "", "text": "HARBOR"},
		],
	},
]
