class_name DistrictOnePopulation
extends Node2D

## Population is intentionally separate from the authored map. Moving traffic
## consumes only the directed Path2D lanes generated by UnifiedRoadNetwork2D;
## pedestrian and parking authored data remain owned by the district layout.

const MODERN_TRAFFIC := preload("res://district/ModernTrafficFactory.gd")
const AUTHORED_PEDESTRIAN := preload("res://district/pedestrians/AuthoredSidewalkPedestrian.gd")
const JUNCTION_TRAFFIC := preload("res://district/roads/traffic/JunctionTrafficController.gd")

@export_range(0, 32) var moving_vehicle_count := 24
@export_range(0, 48) var pedestrian_count := 36
@export_range(0, 24) var parked_vehicle_count := 18

const VEHICLE_ARCHETYPES := [
	"sedan_classic", "taxi_yellow", "sport_coupe", "station_wagon",
	"ranch_pickup", "muscle_classic", "beach_cabriolet", "desert_jeep_4x4",
]
var _layout: Node = null


func _ready() -> void:
	call_deferred("_populate_from_authored_layout")


func _populate_from_authored_layout() -> void:
	_layout = get_tree().get_first_node_in_group("district_one_layout")
	if _layout == null:
		push_error("DistrictOnePopulation requires a node in group district_one_layout")
		return
	if not _layout.has_method("get_pedestrian_routes"):
		push_error("DistrictOneExpansion must expose authored pedestrian routes")
		return
	var graph := _find_unified_road_graph()
	if graph == null:
		push_error("DistrictOnePopulation requires UnifiedRoadNetwork2D.get_graph_data()")
		return
	_ensure_junction_controller(graph)
	# UnifiedRoadNetwork builds in _ready before this deferred population pass.
	# One extra frame also covers a graph provider rebuilt through call_deferred.
	var directed_lanes := _get_unified_directed_lanes(graph)
	if directed_lanes.is_empty():
		await get_tree().process_frame
		directed_lanes = _get_unified_directed_lanes(graph)
	if directed_lanes.is_empty():
		push_error("DistrictOnePopulation found no Path2D in group unified_traffic_lane")
	else:
		_spawn_moving_traffic(directed_lanes)
	_spawn_pedestrians(_layout.get_pedestrian_routes())
	if _layout.has_method("get_parking_spots"):
		_spawn_parked_cars(_layout.get_parking_spots())
	print("DISTRICT_ONE_POPULATED: %d traffic, %d pedestrians, %d parked" % [
		get_tree().get_nodes_in_group("district_one_traffic").size(),
		get_tree().get_nodes_in_group("district_one_pedestrians").size(),
		get_tree().get_nodes_in_group("district_one_parked").size(),
	])


func _find_unified_road_graph() -> Node2D:
	var district_root := get_parent()
	if district_root == null:
		return null
	var candidates: Array[Node] = [district_root]
	candidates.append_array(district_root.find_children("*", "Node2D", true, false))
	for candidate in candidates:
		if candidate is Node2D and candidate.has_method("get_graph_data"):
			var data = candidate.call("get_graph_data")
			if data is Dictionary and (data as Dictionary).has("junctions"):
				return candidate as Node2D
	return null


func _ensure_junction_controller(graph: Node2D) -> Node:
	for candidate in get_tree().get_nodes_in_group("junction_traffic_controller"):
		if candidate.get("graph_source") == graph:
			return candidate
	var controller := JUNCTION_TRAFFIC.new()
	controller.name = "JunctionTrafficController"
	controller.configure_graph_source(graph)
	get_parent().add_child(controller)
	return controller


func _get_unified_directed_lanes(graph: Node2D) -> Array[Path2D]:
	var result: Array[Path2D] = []
	var district_root := get_parent()
	for candidate in get_tree().get_nodes_in_group("unified_traffic_lane"):
		if not candidate is Path2D:
			continue
		if graph.is_ancestor_of(candidate) or (district_root != null and district_root.is_ancestor_of(candidate)):
			result.append(candidate as Path2D)
	result.sort_custom(func(a: Path2D, b: Path2D) -> bool:
		return String(a.get_meta("traffic_lane_id", a.name)) < String(b.get_meta("traffic_lane_id", b.name))
	)
	return result


func _spawn_moving_traffic(lane_paths: Array[Path2D]) -> void:
	if lane_paths.is_empty():
		return
	var spawn_count := mini(moving_vehicle_count, lane_paths.size() * 6)
	if spawn_count == 0:
		return
	var per_route := int(ceil(float(spawn_count) / float(lane_paths.size())))
	for index in spawn_count:
		var lane: Path2D = lane_paths[index % lane_paths.size()]
		var archetype_id: String = VEHICLE_ARCHETYPES[index % VEHICLE_ARCHETYPES.size()]
		var slot_on_route := index / lane_paths.size()
		var route_offset := float(index % lane_paths.size()) * 0.037
		var requested_ratio := fposmod((float(slot_on_route) + 0.32) / float(per_route) + route_offset, 1.0)
		var vehicle := MODERN_TRAFFIC.spawn_moving_vehicle(
			lane,
			"BoroughTraffic_%02d" % (index + 1),
			archetype_id,
			requested_ratio,
			82.0 + float(index % 5) * 7.0,
			index + 8
		)
		vehicle.add_to_group("district_one_traffic")


func _spawn_pedestrians(routes: Array) -> void:
	if routes.is_empty():
		return
	for index in mini(pedestrian_count, routes.size() * 5):
		var points: PackedVector2Array = routes[index % routes.size()]
		if points.size() < 2:
			continue
		var pedestrian := AUTHORED_PEDESTRIAN.new()
		pedestrian.name = "BoroughPedestrian_%02d" % (index + 1)
		pedestrian.district_theme = AnimatedPedestrian3D.DistrictTheme.CITY_DOWNTOWN
		pedestrian.archetype_override = index % 8
		pedestrian.configure_authored_route(points, "borough_walk_%02d" % (index % routes.size()), float(index) * 137.0)
		pedestrian.add_to_group("district_one_pedestrians")
		add_child(pedestrian)


func _spawn_parked_cars(spots: Array) -> void:
	for index in mini(parked_vehicle_count, spots.size()):
		var data: Dictionary = spots[index]
		var archetype_id: String = VEHICLE_ARCHETYPES[(index + 2) % VEHICLE_ARCHETYPES.size()]
		var car := MODERN_TRAFFIC.spawn_parked_vehicle(
			self,
			"BoroughParked_%02d" % (index + 1),
			data.get("position", Vector2.ZERO),
			float(data.get("rotation", 0.0)),
			archetype_id,
			index + 16
		)
		car.add_to_group("district_one_parked")
